#!/bin/bash

#if [ -z "$1" ]
#    then
#     echo "Missing argument ! ! !"
#     echo "use ps command"
#     echo "> ps
#     PID TTY          TIME CMD
#      10 pts/0    00:00:01 bash"
#     echo "Usage: ./pselect <terminal>"
#     echo ""
#     echo " In this case use pts/0"
#     exit
#fi
#terminal=$1
#terminal=`ps | tail -n 1 | rev | cut -d " " -f6 | rev`
terminal=`ps r | cut -d" " -f3 | tail -1` 
HEIGHT=15
WIDTH=90
CHOICE_HEIGHT=13
BACKTITLE="Program selection"
TITLE="Programs list"
MENU="Please select:"

OPTIONS=(1 "getCOVID.sh -  Getting data from Wikipedia site."
         2 "createGraph.sh - Print barg raph form txt files.")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/$terminal)

clear
case $CHOICE in
        1)
	    ./getCOVID.sh
            ;;
        2)
	    clear && ./createGraph.sh
            ;;
        "*")
            echo "Bye Bye :-)"
            exit 0
            ;;

esac
