#!/bin/bash
terminal=`ps | tail -n 1 | rev | cut -d " " -f7 | rev`
HEIGHT=15
WIDTH=90
CHOICE_HEIGHT=13
BACKTITLE="Program selection"
TITLE="Programs list"
MENU="Please select:"

OPTIONS=(1 "getCOVID.sh -  Getting data from Wikipedia site."
         2 "createGraph.sh - Print barg raph form txt files.")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/$terminal)

clear
case $CHOICE in
        1)
            echo "You select getCOVID"
	    ./getCOVID.sh
            ;;
        2)
            echo "You select creategraph"
	    clear && ./createGraph.sh
            ;;
        "*")
            echo "Bye Bye :-)"
            exit 0
            ;;

esac
